[package]
name = "isomorphic-open-hypergraphs"
version = "0.1.0"
edition = "2024"

[dependencies]
open-hypergraphs = { version = "0.2.7", features = ["serde"] }
serde_json = "1.0"
rand = "0.8"
open-hypergraphs-dot = "0.2.1"
graphviz-rust = "0.9.6"
serde = "1.0.228"
